### ISSUE TITLE
Report (max. 4 pages A4) + presentation

### ISSUE THREAD

**Issue by melanger** [JavaCardSpot-dev/ledger-u2f-javacard#6]
- [ ] #7 What functionality is offered + APDU format
- [ ] #8 What sensitive values are protected
- [ ] #9 What cryptographic algorithms and protocols are used
- [ ] #10 What is relevant attacker model
- [ ] #11 What is state model of applet

**Comment by melanger** [comment]
See https://github.com/J08nY/PV204
